version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my-redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-cli:
    image: redis:latest
    container_name: my-redis-cli
    depends_on:
      - redis
    command: ["redis-cli", "-h", "redis", "-a", "junitest"]

volumes:
  redis_data:
  